AWSTemplateFormatVersion: 2010-09-09
Description: |
  The s3izzle
Parameters:
  NAME:
    Type: String
    Default: icullinane-simple-bucket
Resources:
  S3SimpleBucket:
    DeletionPolicy: Retain
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
